State:1
Info:原版 1.8
Logo:pack://application:,,,/Plain Craft Launcher 2;component/Images/Blocks/Grass.png
ReleaseTime:2015-12-03 17:24
VersionFabric:
VersionOptiFine:
VersionLiteLoader:False
VersionForge:
VersionNeoForge:
VersionApiCode:-1
VersionOriginal:1.8
VersionOriginalMain:8
VersionOriginalSub:0
